# Generated by Django 5.2.3 on 2025-06-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='clinic',
        ),
    ]
