# Generated by Django 5.2.3 on 2025-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospitaladmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.AddField(
            model_name='hospital',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact_person_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='fax_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('military', 'Military'), ('trust', 'Trust'), ('ngo', 'NGO')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                setattr(hospital, 'registration_number', f'REG-{str(hospital.id).zfill(5)}')
                and hospital.save()
                for hospital in apps.get_model('core', 'Hospital').objects.all()
            ],
            lambda apps, schema_editor: [
                setattr(hospital, 'registration_number', 'REG-00000')
                and hospital.save()
                for hospital in apps.get_model('core', 'Hospital').objects.all()
            ]
        ),
        migrations.AlterField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(default='REG-00000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
