# Generated by Django 5.2.3 on 2025-06-15 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_hospital_address_hospital_alternate_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='location',
        ),
        migrations.AddField(
            model_name='clinic',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('general', 'General'), ('dental', 'Dental'), ('eye', 'Eye'), ('physiotherapy', 'Physiotherapy'), ('homeopathy', 'Homeopathy'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedic', 'Orthopedic'), ('pediatric', 'Pediatric'), ('gynecology', 'Gynecology'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='cnic_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='clinic',
            name='establishment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='license_number',
            field=models.CharField(default='LIC-00000', max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner_mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clinic',
            name='registration_number',
            field=models.CharField(default='CREG-00000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='street_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
