# Generated by Django 5.2.3 on 2025-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_clinic_location_clinic_alternate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(default='REG-00000', max_length=50),
        ),
    ]
